CREATE TABLE IF NOT EXISTS User (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(120) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    password VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS Place (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(200) NOT NULL,
    coordinate VARCHAR(60) NOT NULL,
    direction VARCHAR(120) NOT NULL,
    img VARCHAR(120) NOT NULL
    type VARCHAR(80) NOT NULL,
    counter INT DEFAULT 0
);